<a href="https://colab.research.google.com/github/phu-minh/CS116.M11.KHTN/blob/main/19520218_NguyenMinhPhu_CS116_BT8_sklearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


#Hồi Quy - Linear Regression


In [1]:
from google.colab import drive
drive.mount('/content/drive')
%cd "/content/drive/MyDrive/CS116"

Mounted at /content/drive
/content/drive/MyDrive/CS116


In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import LinearRegression
from statistics import mean
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split

In [3]:
def pipeline(x, y, model): 
    accuracies = []
    kf = KFold(n_splits=5)
    for train_index, test_index in kf.split(x):
          x_train, y_train = x[train_index], y[train_index]
          x_test, y_test = x[test_index], y[test_index]
          model.fit(x_train, y_train)

          score = model.score(x_test, y_test)
          accuracies.append(score)
    return accuracies

# Salary Data

In [4]:
df1 = pd.read_csv('Salary_Data.csv')
df1.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [5]:
x1 = np.array(df1['YearsExperience']).reshape((-1,1))
y1 = np.array(df1['Salary'])

In [6]:
print(x1[[1,2,3,4,5]])

[[1.3]
 [1.5]
 [2. ]
 [2.2]
 [2.9]]


In [7]:
print(y1[:5])

[39343. 46205. 37731. 43525. 39891.]


In [8]:
X_train, X_test, y_train, y_test = train_test_split(x1, y1, test_size=0.2)

In [10]:
model = LinearRegression()
model.fit(X_train, y_train)

model.score(X_test, y_test)

0.9619476371639156

# 50_Startups

In [11]:
# show data structure
df2 = pd.read_csv('50_Startups.csv')
df2.head(10)

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94
5  131876.90        99814.71        362861.36    New York  156991.12
6  134615.46       147198.87        127716.82  California  156122.51
7  130298.13       145530.06        323876.68     Florida  155752.60
8  120542.52       148718.95        311613.29    New York  152211.77
9  123334.88       108679.17        304981.62  California  149759.96

In [12]:
profit = df2['Profit']
df2 = df2.drop('Profit',axis = 1)

one_hot = pd.get_dummies(df2['State'])
# Drop column 
df2 = df2.drop('State',axis = 1)
# Join the encoded df
df2 = df2.join(one_hot)
df2 = df2.join(profit)


In [13]:
df2.head(10)

R&D Spend  Administration  Marketing Spend  ...  Florida  New York     Profit
0  165349.20       136897.80        471784.10  ...        0         1  192261.83
1  162597.70       151377.59        443898.53  ...        0         0  191792.06
2  153441.51       101145.55        407934.54  ...        1         0  191050.39
3  144372.41       118671.85        383199.62  ...        0         1  182901.99
4  142107.34        91391.77        366168.42  ...        1         0  166187.94
5  131876.90        99814.71        362861.36  ...        0         1  156991.12
6  134615.46       147198.87        127716.82  ...        0         0  156122.51
7  130298.13       145530.06        323876.68  ...        1         0  155752.60
8  120542.52       148718.95        311613.29  ...        0         1  152211.77
9  123334.88       108679.17        304981.62  ...        0         0  149759.96

[10 rows x 7 columns]

In [14]:
y2 =  df2['Profit'].to_numpy()
x2 = df2.drop('Profit',axis = 1).to_numpy()

In [15]:
x2[:5]

array([[1.6534920e+05, 1.3689780e+05, 4.7178410e+05, 0.0000000e+00,
        0.0000000e+00, 1.0000000e+00],
       [1.6259770e+05, 1.5137759e+05, 4.4389853e+05, 1.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [1.5344151e+05, 1.0114555e+05, 4.0793454e+05, 0.0000000e+00,
        1.0000000e+00, 0.0000000e+00],
       [1.4437241e+05, 1.1867185e+05, 3.8319962e+05, 0.0000000e+00,
        0.0000000e+00, 1.0000000e+00],
       [1.4210734e+05, 9.1391770e+04, 3.6616842e+05, 0.0000000e+00,
        1.0000000e+00, 0.0000000e+00]])

In [16]:
y2[:5]

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94])

In [17]:
X_train, X_test, y_train, y_test = train_test_split(x2, y2, test_size=0.2, random_state=1)

model = LinearRegression()
model.fit(X_train, y_train)

model.score(X_test, y_test)

0.9649618042060305